
project_id = "hunlwxpizenlsqcghffy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false
port = 54327

# Configuración para la función polls-api para que no requiera autenticación
[functions.polls-api]
verify_jwt = false

# Configuración para la función de creación de políticas de buckets públicos
[functions.create-bucket-policy]
verify_jwt = false
